# Generated by Django 3.2.6 on 2022-02-19 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ceef9d8c-00f4-4b98-aafd-8281e0333259'), editable=False, primary_key=True, serialize=False),
        ),
    ]
