# Generated by Django 3.2.6 on 2022-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_createblogmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
