# Generated by Django 3.2.6 on 2022-02-19 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_createblogmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5b9e3ca-f73a-49b6-957d-0cbdd86db5b4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
