# Generated by Django 3.2.6 on 2022-02-19 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_createblogmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71a9623d-2d69-4075-9af2-fec0d4f28f65'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
