# Generated by Django 3.2.6 on 2022-02-20 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_createblogmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createblogmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='createblogmodel',
            name='create_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.user', to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dc6cad9-55cf-456e-8180-12564780b90c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
