# Generated by Django 3.2.6 on 2022-02-20 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220220_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b139b4d1-d0aa-4824-b1b2-e255619f9977'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
