# Generated by Django 3.2.6 on 2022-02-20 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_createblogmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7348054-7038-414d-85d4-05c2f7e9c3df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
