# Generated by Django 3.2.6 on 2022-02-20 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_createblogmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblogmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b383764e-b83a-424c-855a-2ba9dfc7752f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
